[browser]
gatherUsageStats = false

[server]
enableStaticServing = false
enableXsrfProtection = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[global]
developmentMode = false
showWarningOnDirectExecution = false
